baseURL: 'https://marcosramos.dev/'
languageCode: en-us
title: Marcos Ramos
theme: PaperMod
enableEmoji: true
enableRobotsTXT: true

googleAnalytics: G-4M93XLTSFC

params:
  env: production
  title: Marcos Ramos
  keywords:
    - Blog
    - Portfolio
  author:
    - Marcos Ramos
  comments: false
  ShowShareButtons: true
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowToc: true
  homeInfoParams:
    Title: "Hello \U0001F44B\U0001F3FB"
    Content: |
      Welcome to my personal website!

      Here you will find some blog posts, contact
      information and more!
  socialIcons:
    - name: github
      url: 'https://github.com/msramos'
    - name: twitter
      url: 'https://twitter.com/rmsmrcs'
    - name: linkedin
      url: 'https://www.linkedin.com/in/rmcsmrcs'
    - name: telegram
      url: 'https://t.me/MarcosRamos'
    - name: email
      url: mailto://rms.mrcs@gmail.com
    - name: rss
      url: index.xml

  analytics:
    google:
      SiteVerificationTag: "G-4M93XLTSFC"

  editPost:
    URL: "https://github.com/msramos/msramos.github.io/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

permalinks:
  blog: 'blog/:year/:month/:title/'

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  tag: tags
  series: series

menu:
  main:
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 10
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40

markup:
  goldmark:
    renderer:
      unsafe: true
